### ISSUE TITLE
text-decoration: blink;

### ISSUE THREAD

**Issue by Abromeit** [contra/blink-polyfill#1]
When `<blink>` became invalid, 
many of us started using something like
`.highlight{ text-decoration: blink; }` 

A perfect polyfill would care about this too. (But involves JS AFAIS.)

**Comment by su-narthur** [comment]
@contra Maybe I'm reading him wrong, but I think he means it would be nice if the polyfill also re-enabled `text-decoration: blink;` in browsers that no longer support it.

**Comment by contra** [comment]
@su-narthur Guess I misunderstood - would require some JS to do this, will take a PR if anyone wants to swing at it
